server:
  port: 9001

# server:
#   port: 8041

spring:
  application:
    name: user-service

eureka:
  instance:
    register-with-eureka: true
    fetch-registry: true
    hostname: e_server
    serviceUrl:
      defaultZone: http://e_server:8761/eureka  
    