server:
  port: 9001

# server:
#   port: 8041

spring:
  application:
    name: user-service

eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    